### PR TITLE
Invalid data on open

### PR DESCRIPTION
**Pull request by mycroes**
In hope to get more detail for connection issues like #194 and perhaps #179.

### CODE REVIEW

**Comment by Zuendelmeister** [comment]
Hi @mycroes 
I tried it again with the lates version on the develop branch. Unfortunately the outcome is still the same.
image

**Comment by Zuendelmeister** [comment]
Hi again, do you have new info on this? I'm on vacation soon and realy would like to see this fixed beforehand. Can I somehow provide further assistance somehow?

**Comment by Zuendelmeister** [comment]
Do you have a plan when this could be fixed?

**Comment by mycroes** [comment]
Hi @Zuendelmeister,

That's actually good news, because I was trying to eliminate differences between Sally7 and S7NetPlus with regards to connection initialization. However, since it doesn't work in both I now know I need to shift my focus elsewhere :wink: . I will take another look at the node-red support and see if there's something different there. Could you perhaps point me to the node-red plugin you're using?

**Comment by Zuendelmeister** [comment]
Hi again,

I cannot get the code to work with sally 7:
image

I also tried to use "ref" but no luck.

I also tried it with the S7 1500 but no luck either:
image

Adding tracing is probably the best right now.
Thanks!

Best regards,
Zuendelmeister

**Comment by Zuendelmeister** [comment]
Hi @mycroes,
can I do anything else to help you?

Best regards,
Zuendelmeister

**Comment by mycroes** [comment]
Hi @Zuendelmeister 

> can I do anything else to help you?

Yes! Although I didn't implement logging, I though I'd give NodeS7 a spin to see if I could find something interesting there, and I did. I compared CR (connection request) of NodeS7 with Sally7 for the parameters I gave you, and there was a difference in both source and destination TSAP in the CR. I'm guessing this is the reason why it's not working (with S7NetPlus *and* Sally7), but there are some other minor differences as well. Can you test the following with Sally7?

```csharp
var sourceTsap = new Tsap {Channel = 1, Position = 0};
var destTsap = new Tsap {Channel = 1, Position = 2};
var conn = new S7Connection(ipOrHostname, sourceTsap, destTsap);
await conn.Open();
```

If this works I'll add the ID's to S7NetPlus. Thanks for your immense patience so far.

**Comment by Zuendelmeister** [comment]
Hi @mycroes 
thanks for the code! I updated C# to Version 7.2 and now I can work with "in", so I could test it.
Unfortunately it didn't work either:
image

What else could we try?
Thanks again.

Best regards,
Zuendelmeister

**Comment by mycroes** [comment]
Hi @Zuendelmeister,

Yes, I can mimick the other fields that are different from NodeS7 as well, I'll try to make the changes this evening.

**Comment by mycroes** [comment]
Hi @Zuendelmeister,

I have good news and bad news. The good news is I wrote a sample that you should be able to try, the bad news is that it's ugly. Also, make sure you change the address for `di` so it points to something valid (else they'll all fail).

Here's the (ugly) code:

```c#
using System;
using System.Net.Sockets;
using System.Reflection;
using Sally7;
using Sally7.Protocol.Cotp;

namespace Sample
{
    class Program
    {
        private const int Rack = 0;
        private const int Slot = 2;

        private static object GetFieldValue(S7Connection connection, string name)
        {
            var fi = typeof(S7Connection).GetField(name, BindingFlags.Instance | BindingFlags.NonPublic) ??
                throw new Exception($"Couldn't find field with name '{name}'.");
            return fi.GetValue(connection) ?? throw new Exception($"No value found for field '{name}'.");
        }

        private static void AlternateConnect(string host, S7Connection connection, byte[] cr, byte[] cs)
        {
            var client = (TcpClient) GetFieldValue(connection, "client");

            client.Connect(host, 102 /* IsoOverTcpPort */);

            var buffer = new byte[100];
            var stream = client.GetStream();
            stream.Write(cr, 0, cr.Length);

            var len = ReadTpkt(stream, buffer);
            // Let's just assume this is correct, since it previously has never errored.

            stream.Write(cs, 0, cs.Length);
            len = ReadTpkt(stream, buffer);
            // Let's assume this either errors, or is correct.

            var pduSize = buffer[len - 2] << 8 | buffer[len - 1];
            buffer = new byte[pduSize];
            typeof(S7Connection).GetField("buffer", BindingFlags.Instance | BindingFlags.NonPublic).SetValue(connection, buffer);

            Console.WriteLine($"Response PDU Size: {pduSize}");
        }

        private static int ReadTpkt(NetworkStream stream, byte[] buffer)
        {
            var len = stream.Read(buffer, 0, 4);
            if (len < 4)
                throw new Exception($"Error while reading TPKT header, expected 4 bytes but received {len}.");

            if (buffer[0] != 3) throw new Exception("Invalid TPKT version");
            if (buffer[1] != 0) throw new Exception("Invalid reserved byte");

            var msgLen = buffer[3]; // Slight hack, length for CR/CS is never > 255
            
            len = stream.Read(buffer, 4, msgLen);
            if (len != msgLen - 4)
            {
                throw new Exception($"Error while reading TPKT data, expected {msgLen} bytes but received {len}.");
            }

            return msgLen;
        }

        static void Main(string[] args)
        {
            var nodeS7cr = new byte[] {3, 0, 0, 22, 17, 224, 0, 0, 0, 2, 0, 192, 1, 10, 193, 2, 1, 0, 194, 2, 1, 2};
            var sally7cr = new byte[] {3, 0, 0, 22, 17, 224, 0, 0, 0, 0, 0, 192, 1, 11, 193, 2, 1, 0, 194, 2, 1, 2};
            var sally7crPdu960 = nodeS7cr;

            var nodeS7cs = new byte[]
            {
                3, 0, 0, 25, 2, 240, 128, 50, 1, 0, 0, 0, 0, 0, 8, 0, 0, 240, 0, 0, 8, 0, 8, 3, 192
            };
            var sally7cs = new byte[]
            {
                3, 0, 0, 25, 2, 240, 128, 50, 1, 0, 0, 1, 0, 0, 8, 0, 0, 240, 0, 0, 1, 0, 1, 7, 128
            };
            var sally7csPdu960 = new byte[]
            {
                3, 0, 0, 25, 2, 240, 128, 50, 1, 0, 0, 1, 0, 0, 8, 0, 0, 240, 0, 0, 1, 0, 1, 3, 192
            };
            var sally7csAltHeader = new byte[]
            {
                3, 0, 0, 25, 2, 240, 128, 50, 1, 0, 0, 0, 0, 0, 8, 0, 0, 240, 0, 0, 1, 0, 1, 7, 128
            };

            var sourceTsap = new Tsap {Channel = 1, Position = 0};
            var destTsap = new Tsap {Channel = 1, Position = 2};

            var conn = new S7Connection("127.0.0.1", sourceTsap, destTsap);
            var di = new DataBlockDataItem<int> {DbNumber = 9, StartByte = 2};

            try
            {
                AlternateConnect("127.0.0.1", conn, nodeS7cr, nodeS7cs);
                conn.Write(di).GetAwaiter().GetResult();
                conn.Read(di).GetAwaiter().GetResult();
                conn.Close();
            }
            catch (Exception e)
            {
                conn.Close();
                Console.WriteLine($"NodeS7 init failed: {e}");
            }

            try
            {
                conn = new S7Connection("127.0.0.1", sourceTsap, destTsap);
                AlternateConnect("127.0.0.1", conn, sally7crPdu960, sally7csPdu960);
                conn.Write(di).GetAwaiter().GetResult();
                conn.Read(di).GetAwaiter().GetResult();
                conn.Close();
            }
            catch (Exception e)
            {
                conn.Close();
                Console.WriteLine($"Sally7 PDU 960 init failed: {e}");
            }

            try
            {
                conn = new S7Connection("127.0.0.1", sourceTsap, destTsap);
                AlternateConnect("127.0.0.1", conn, sally7cr, sally7csAltHeader);
                conn.Write(di).GetAwaiter().GetResult();
                conn.Read(di).GetAwaiter().GetResult();
                conn.Close();
            }
            catch (Exception e)
            {
                conn.Close();
                Console.WriteLine($"Sally7 alt header init failed: {e}");
            }

            try
            {
                conn = new S7Connection("127.0.0.1", sourceTsap, destTsap);
                AlternateConnect("127.0.0.1", conn, sally7cr, sally7cs);
                conn.Write(di).GetAwaiter().GetResult();
                conn.Read(di).GetAwaiter().GetResult();
                conn.Close();
            }
            catch (Exception e)
            {
                conn.Close();
                Console.WriteLine($"Sally7 init failed: {e}");
            }

            Console.WriteLine("Done, press any key...");
            Console.ReadKey();
        }
    }
}
```

**Comment by Zuendelmeister** [comment]
Hi @mycroes,
thank you so much for your effort!
This is what came out:

```
Response PDU Size: 240
Response PDU Size: 240
Sally7 alt header init failed: System.Exception: Error while reading TPKT header, expected 4 bytes but received 0.
   bei Sample.Program.ReadTpkt(NetworkStream stream, Byte[] buffer) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 50.
   bei Sample.Program.AlternateConnect(String host, S7Connection connection, Byte[] cr, Byte[] cs) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 34.
   bei Sample.Program.Main(String[] args) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 123.
Sally7 init failed: System.Exception: Error while reading TPKT header, expected 4 bytes but received 0.
   bei Sample.Program.ReadTpkt(NetworkStream stream, Byte[] buffer) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 50.
   bei Sample.Program.AlternateConnect(String host, S7Connection connection, Byte[] cr, Byte[] cs) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 34.
   bei Sample.Program.Main(String[] args) in C:\Users\<NAME>\source\repos\S7NetPlusAndSally7TestNet\S7NetPlusAndSally7TestNet\Program.cs:Zeile 137.
Done, press any key...
```

Best regards,
Zuendelmeister

**Comment by mycroes** [comment]
Hi @Zuendelmeister,

No, thank you for your effort and keeping up with this. From what I see the PLC only accepts a PDU size up to 960 and rejects the connection if higher is requested (which is what Sally7 does and I think I might have changed this in S7NetPlus as well at some point). I'll see if I'll lower it to 960 or allowing an override (both for Sally7 and S7NetPlus). Either way, thanks again for your effort, I'll try to fix this in S7NetPlus ASAP.

**Pull request merged**
