### PR TITLE
Change S7 200 remote TSAP to 10.01

### PR DESCRIPTION
**Pull request by mycroes**

### CODE REVIEW

**Comment by jaydeep6720** [comment]
which code you want me to check ?

**Comment by mycroes** [comment]
@jaydeep6720  Just this one should suffice: 0750ee006f2154c5a7ada5b00398ee135d2f085d

**Comment by jaydeep6720** [comment]
Please find the attached screenshot of revised code 0750ee0;
attached both result screenshots
as i told you in last email;

Initialised code
Plc ROT = new Plc(CpuType.S7200, "192.168.2.1", 0, 0);

ABocde is not connected to S7200 SMart PLC having an onboard Ethernet port.
If i change PLC Cpu type to 300, it is very well performing all operations;

 Plc ROT = new Plc(CpuType.S7300, "192.168.2.1", 0, 0);

**Comment by mycroes** [comment]
So in short, if you use `CpuType.S7300` you can actually connect to an S7200 Smart?

**Comment by jaydeep6720** [comment]
Yes, that is correct.
SO you just need to add Enum plc type S7200Smart which uses connection
request data of S7300

**Comment by mycroes** [comment]
@jaydeep6720 #396 adds `CpuType.S7200Smart`, which behaves just like S7 300/400/1200/1500 with regards to TSAP calculation.

**Pull request merged**
