### PR TITLE
Logo 8 connection support

### PR DESCRIPTION
**Pull request by mycroes**
Concurrency is not supported and this might cause Logo8 to bail. Addresses #179.

### CODE REVIEW

**Comment by mycroes** [comment]
@JekRock @rapha-dev Can you guys test that this PR still works for the PLC types you have?

**Comment by JekRock** [comment]
@mycroes do I need a develop branch to test this PR?

**Comment by mycroes** [comment]
@JekRock No you need to checkout the actual commit:
```
git fetch origin 0d99f8fa2f4250cae2bda7511bed38a3aad4d814
git checkout -B logo-8-pr FETCH_HEAD
```

**Comment by mycroes** [comment]
Abandoning, only thing in here that could've still been of use are the comments on the message byte array.

**Pull request closed without merging**
