### PR TITLE
Add DTL type

### PR DESCRIPTION
**Pull request by scamille**
Add new class Types.Dtl by taking the DateTime code and adjusting things.

Includes Unit Test (which is just the DateTime one adjusted for DTL as well)

I had an existing DTL converter to work from, but https://support.industry.siemens.com/cs/mdm/109773506?c=93833257483&lc=en-WW describes the data type pretty well.

### CODE REVIEW

**Comment by mycroes** [comment]
@scamille Although there's no code in #267, I assume this implements what's described there? Will try to review this ASAP.

**Comment by scamille** [comment]
No this is not in any way associated with #267 , nor did I get my implementation details from there.

If you want me to make any changes, eg. to naming things, just let me know.

Some of the implementation details (eg. using MemoryStream in ToByteArray) where done so I could reuse the existing Types.Word and Types.DWord implementions to do the conversion for year and nanoseconds.

**Comment by mycroes** [comment]
Hi @scamille I know there's no association (and there's no code in #267 either, so nothing you could've used in that sense), but if this PR conveys the same intention as #267 than I can close that one as well when this is merged 😉

**Comment by scamille** [comment]
Yes of course. Since there is no code in the other PR, I can just assume that based on its title it attempted to implement the same thing as I did :-)

About Naming: Do you prefer Dtl / DTL, or DateTimeLong? (Not to be confused with LDT (DATE_AND_LTIME) )

**Comment by mycroes** [comment]
Honestly I'd prefer DateTimeLong, because it's most precise and with a proper IDE (or R# 😉) typing dtl will complete to DateTimeLong just as well. OTOH I'm not sure about the current conventions, they're not mine (I only did 'fixes' and write-multiple support, almost all of the other work is before I maintained S7NetPlus).

**Comment by mycroes** [comment]
Released as [0.6.0](https://github.com/S7NetPlus/s7netplus/releases/tag/v0.6.0).

**Pull request merged**
