### PR TITLE
Add support for DTL type in S71200 and S71500

### PR DESCRIPTION
**Pull request by Jason-Jelks**
DT Format is not natively supported by S71200 and S71500. It was changed to DTL (DateTimeLong). However S7200, S7300 & S7400 currently only support DT type format. I will add the required parsing to translate Windows DateTime.UTC to and from S71200/1500.

Additionally, the "Class" functions do not support DateTime, of any type (DT, DTL), to be part of the parsed Class structure. This can be supported by adding DI to the parsing methods for the instanced PLC.

### CODE REVIEW

**Comment by mycroes** [comment]
Hi @Jason-Jelks, sorry for this super late reply. I don't see any changes while I'd guess you must have made some. Do you want to give this another try?

**Comment by mycroes** [comment]
Obsoleted by #284.

**Comment by Jason-Jelks** [comment]
My apologies, I was traveling and unable to get back to this. It appears that #284 made very similar changes to what I did for the DateTimeLong. Thanks for picking up the ball!

**Comment by mycroes** [comment]
No worries, thanks for your response!

**Comment by Jason-Jelks** [comment]
FWIW - I did review #284 and merged some of his changes to mine, but left some of my changes for optimizations. I also have changes to the Class.cs which you can review and see if they work for you or not.

**Pull request closed without merging**
