### PR TITLE
Add unit test to ensure a connection has been properly closed

### PR DESCRIPTION
**Pull request by scamille**
If canceled during data transmission, #349 adds code to ensure that the connection automatically gets canceled.

Add a test to ensure this works.
Also, add an inverted version to ensure that cancellation before sending data does not result in cancellation.

### CODE REVIEW

**Comment by scamille** [comment]
Works on my machine :-/

**Comment by mycroes** [comment]
I get the same error locally, pay attention that it only happens on net452, not the other targets.

**Comment by mycroes** [comment]
Seems to me the issue is with `cancellationSource.CancelAfter(TimeSpan.FromMilliseconds(5))`, not sure why that's included in both tests (I think it shouldn't be in either...).

**Comment by mycroes** [comment]
The fact that the tests now fail on a single platform is really good though. I still only have AppVeyor as required check, but I'm considering to make them all required.

**Comment by scamille** [comment]
Right I thought I removed that line, that of course explains it, thanks.

It might sense to wait a bit more to see how reliable the new CI actions are. On the other I do know from the simulation craft/simc project that they are pretty reliable, since we have a lot more commits and longer tests over there, but not any .NET. 
Macos jobs can sometimes fail but it is still rare.

**Comment by mycroes** [comment]
Thanks a lot @scamille!

**Pull request merged**
