### PR TITLE
Fixed size reads

### PR DESCRIPTION
**Pull request by jakob-ledermann**
solves #283.

Submitted as draft and open for editing so you can build upon my code. I hope we can achieve an agreement on the course of solution quickly.

I propose further discussions are moved from the issue to this place.

### CODE REVIEW

**Comment by scamille** [comment]
One thing I still don't understand is why with just your initial ReadFixed implementation this would result in a infinite blocking compared to the current code.

With the current code, any read/write blocks will time out based on what is set in https://github.com/S7NetPlus/s7netplus/blob/develop/S7.Net/PLC.cs#L210 to the Receive and Send Timeout.

With the ReadFixed implementation, you might in the worst case wait longer if you get your whole message 1 byte after another. As soon as you get 0 bytes back (EOF), you bail as well.

Since even with the current implementation, the first read call could block indefinitely instead of giving you less bytes than requested, this can block indefinitely as well. We might want to change the default at https://github.com/S7NetPlus/s7netplus/blob/develop/S7.Net/PLC.cs#L21 to something more sensible, but that is another topic.

Or am I missing something?

**Comment by jakob-ledermann** [comment]
Focusing on the non async implementation, the current implementation does a special casing of Networkstream and a generic Stream implementation, that can not block as I don't know about any Stream implementation, that CanSeek and blocks on read, any other stream must support timeouts and have a timeout set earlier than never.

The special case for NetworkStream checks whether data are available and only reads when data is available (it is much closer to the behaviour on nonblocking linux sockets) and then blocks the current thread for a short amount of time (originally Thread.Sleep, but replaced with SpinWait as it was the first way to block the current thread supported on .Net Standard 1.3) the potentially blocking code is only entered, when it can not block. Given there are no two threads or tasks reading at the same time, which is a bad idea for different reasons.

As I somewhere in the documentation a remark the connection should be closed after a readtimeout, I tried to avoid that situation, in addition to avoiding changing the default in https://github.com/S7NetPlus/s7netplus/blob/develop/S7.Net/PLC.cs#L21 as I wasn't sure whether this has additional side effects, I am missing.

**Comment by scamille** [comment]
I took your first two commits, and adjusted some things, and in particular the Unit Test. I added a fake stream giving 1 byte at a time. This breaks the previous S7Net code without the ReadFixed extensions, without introducing any delay based special cases for now.
See https://github.com/S7NetPlus/s7netplus/compare/develop...scamille:fb-readFixed

What do you think?

**Comment by jakob-ledermann** [comment]
I think the name ReadExact is a better name for ReadFixed (I read it in the [rust documentations](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact) and liked it)
If the default ReadTimeout is changed I think that would be a workable solution.

I'm not completly happy with the special casing of the networkstream in my current implementation.
The current set of unit tests does not catch the case where the answer is malformed (reports a different length than the sent length) and I would prefer the message to fail in this case vs. endlessly blocking the users code or even having two active reads on the connection active at the same time.

**Comment by scamille** [comment]
My plan is to investigate what default timeouts are set for a connection and maybe we can use those. I would assume that .NET or your OS makes a sensible choice for those.

If we make the custom timeout variables in the PLC object nullable this could represent this "default" state.

And yes ReadExact sounds good, I just did not change it. My commit was just intended as a quick hack and would need cleanup anyway.

**Comment by scamille** [comment]
> The current set of unit tests does not catch the case where the answer is malformed (reports a different length than the sent length) and I would prefer the message to fail in this case vs. endlessly blocking the users code or even having two active reads on the connection active at the same time.

What exactly do you mean with this?

I think we can safely assume that a call to ```var byteRead = Stream.Read(buffer, offset, count);``` will have put exactly bytesRead number of bytes into the buffer starting from position offset. Otherwise quite a lot is broken with any .NET Stream implementation.

I you are talking about the 2-phase TPKT Reads: Yes it could be that the first packet receives a malformed length (eg. 65k) and you will then try to get that amount of bytes from the stream.
But unless you have a malicious attacker only giving you 1 byte at a time and thus increasing your total timeout time for the whole request, this should make no difference to the current implementation. Once you get a Read Timeout you also will bail out of ReadExact through an exception.
And if you have no Read Timeout at all, you can already block on the very first Read call forever.

So my main point is: Adding ReadExact likely does not make the timeout behaviour of the library worse compared to the current code in any realistic way.

And since this should definitely fix problems people have when receiving partial responses and getting Exceptions, I think we should resolve this with just those changes for now.

It might certainly be worth thinking about having timeout and async cancellation options on all public PLC functions, providing a fixed and reliable timeout for the complete operation. But again, different topic.

**Comment by jakob-ledermann** [comment]
> So my main point is: Adding ReadExact likely does not make the timeout behaviour of the library worse compared to the current code in any realistic way.

This is actually a valid point.

And yes I was talking about malicious (or erroneous) TPKT datagrams. There is a second bigger issue, which is also in my opinion of topic for now: I managed to send a second request to the plc before the first one was answered by the plc.

So I agree with your PR variant #291 for now and set a usefull readtimeout in my use case.
Unfortunatly DataAvailable is not part of the standard Stream-API so my speciallisation on NetworkStream can not be applied generically and also not tested easily.

**Comment by scamille** [comment]
As far as I understand it, the S7 protocol would allow sending a "identifier" with each request, and you can expect to get that identifier back in the response from the PLC.

S7Net.Plus just always sends the same identifier (0 I believe) and does not check anything. We could check that, further increasing robustness.

But one fundamental limitation of the library certainly is that for the single socket we have per PLC, there can only be 1 request active during any time. Having multiple requests would require a fundemantally different architecture, and make things way way too complicated.

The appropriate solution for S7.NetPlus would be to either add some locks or at least be informative about it being neither multi-thread-safe nor truly suitable for unlocked async operations.

I personally have async locks available for the software where I integrated S7.NetPlus library, so did not encounter any of the problems. But I expect that specifically for users of the async api, this could lead to some confusion.

**Pull request closed without merging**
