### PR TITLE
Refactor TSAP related code

### PR DESCRIPTION
**Pull request by mycroes**

### CODE REVIEW

**Review by scamille — APPROVED** [review]

**Comment by mycroes** [comment]
Still work in progress, thanks for the early review though!

**Comment by scamille** [comment]
draft \*cough\* ;)

So far this is still quite a simple refactoring, but makes everything much more organized. I like the new version of the ```InvalidRackOrSlot``` function. There is still minor duplication of the min and max value, but that is ok since they are at least on the same line now.

**Comment by mycroes** [comment]
I guess it's ready now though, asked some people in issues to test this, not sure if I'm gonna wait until they report back though, seeing as that might take months....

**Comment by scamille** [comment]
As far as I understand those issues, the problem with the S7 200 connection already exists with the current version. So trying out the new value for the local tsap can't really make it worse, and if #332 is correct it should be resolved.

So probably best to just merge the refactoring, and even if the S7 200 connection still does not work it can always be given another try later.

Of course it would be nice to get a confirmation about it if you want to do a new release based on the changes.

**Comment by mycroes** [comment]
Thanks again, merging as-is.

**Pull request merged**
