### PR TITLE
Fixed byte to bit.

### PR DESCRIPTION
**Pull request by nick-kramer117**

### CODE REVIEW

**Comment by timverwaal** [comment]
I submitted a very similar PR #246. Thus, #277, #278 and #246 can be pulled as one item I think. Hopefully it will be part of a next release.

**Comment by mycroes** [comment]
Sorry for the massive delay in response and releases. I hope to catch up on all these very soon (this week or next week). For now, thanks for the effort.

**Comment by nick-kramer117** [comment]
Thanks for the S7NetPlus library.  I would like to take part in the further
development of this library.  At the moment I have rebuilt this library and
added it to my GitHub and Nuget.org pages with a link to the source code.
Do you mind if I develop it in parallel with your Library?  or can you add
me, a group of developers, of this library?

чт, 6 авг. 2020 г., 8:17 Michael Croes <notifications@github.com>:

**Comment by mycroes** [comment]
Hi @nick-kramer117 ,

Sorry for my late reply. I will happily accept PR's and I will try to merge them quicker (and do releases when changes get merged). I wouldn't mind adding more developers either, but I would mind if the code would get even messier than it already is. This honestly isn't my library either, I only made some minor contributions while most of the work has been done by others way before I ever got involved. Unfortunately the previous developers and maintainers lost their need and/or interest and as such development has slowed down.

There's actually a few things that I intend to do with S7NetPlus (short term, as far as that'll work):
- Improve connect exception details, because it's the major reason for bugs
- Add a sample project
- Provide a synchronized implementation

I'd love someone else to contribute to this though, that'll also motivate me more to spend time on S7NetPlus. Last but not least, I'm not maintaining any other projects where people other than me contribute, so maybe I can add you as contributor with limited permissions (at first), but I'd actually have to look into what is feasible in that sense.

Let me know what you think about all this, I especially don't want to scare you off, the project can use contributors.

**Pull request closed without merging**
