### PR TITLE
Remove IsAvailable, document IsConnected

### PR DESCRIPTION
**Pull request by mycroes**
Addresses #275, #252, #208, #154.

### CODE REVIEW

**Review by scamille — COMMENTED** [review]
At first I thought it might be a good idea to just let IsAvailable call IsConnected first, and only if it is not try to connect to the PLC.

But on the other hand, IsAvailable is just a property and tried to do too much, hiding large function calls in it.

So I think it is a sensible choice to just force users to do the Open() call themselves, with all the exception handling necessary for it.
It might even be worth deprecating IsAvailable and pointing to IsConnected.

**Comment by mycroes** [comment]
Hi @scamille, Thanks for taking a peek at this. I was actually slightly confused (as you noticed from my comments with regards to IsConnected on issues) between IsAvailable and IsConnected. I was also thinking about removing IsAvailable altogether. Either way, I was short on time yesterday, so I haven't made up my mind yet. 😄

**Comment by scamille** [comment]
I do like the comments, it really highlights the problems with relying on IsConnected giving the full truth about the connection status.
Even if it would send a keepalive/other dummy data, it would still only give you the IsConnected status at that point of time. A Read/Write after that could still run into a unconnected connection and needs to handle it somehow gracefully. 

You should be able to reference the IsConnected XML documentation from IsAvailable with /// <inheritdoc cref="Plc.IsConnected"/>

And yes adding [Deprecated] would be appropriate, maybe with some words about calling Open() yourself. We certainly don't need IsConnected twice forever.

**Comment by mycroes** [comment]
The comment actually comes from TcpClient.Connected. I think I might just remove IsAvailable altogether, this breaks it anyway for people relying on it to connect this way...

**Pull request merged**
