### PR TITLE
Change test project to a fixed win-x64 runtime identifier and upgrade…

### PR DESCRIPTION
**Pull request by scamille**
… Snap7

Downlaoded Snap7 1.4.2 64bit DLL from https://sourceforge.net/projects/snap7/files/

### CODE REVIEW

**Comment by mycroes** [comment]
Hi @scamille, please rebase this one as well. It seems to build/test just fine on AppVeyor as well, so I don't see much reason not to merge this.

**Comment by scamille** [comment]
I think the original motivation was that this might also reduce sporadic Unit Test failures, even though I have no clue if it does make a difference.

**Comment by scamille** [comment]
Looks like this might really help with sporadic tests failing in CI, in particular T33_WriteLargeByteArray

**Comment by scamille** [comment]
Going to retract this, as #306 contains both the upgraded Snap7 library as well as some other, better adjustments than this.

**Pull request closed without merging**
